engines:
    radon:
        enabled: true
        config:
            threshold: 'B'
#    pep8:
#        enabled: true
ratings:
    paths:
    - "**.py"
exclude_paths:
- "tests/*"
- "ndr_webui/static/bootstrap"
